"$schema" = "https://ubcode.useblocks.com/ubproject.schema.json"

[needs]
id_required = true
build_json = true

[[needs.types]]
directive = "req"
title = "Requirement"
prefix = "REQ_"

[[needs.types]]
directive = "spec"
title = "Specification"
prefix = "SPEC_"
